### ISSUE TITLE
Additional metadata for image manifests

### ISSUE THREAD

**Issue by wiedi** [joyent/sdc-imgapi#4]
It would be good to have a place to put additional metadata in image manifests similar to what is customer_metadata in vm manifests (e.g. object with key=value pairs).

The imgapi should not care about the value of this property but store it and deliver it transparently. Also imgadm should support this if implemented.

There are a few usecases where additional information about images would be useful for external consumers:
- describing what keys in customer_metadata are accepted by this image (for each key specify the datatype, description, ...)
- cryptographically signing other values of the manifest (e.g. sha(uuid+owner+name+version+files))

Having a place to store such information with the image manifest would help with these and future uses.

**Comment by lloydde** [comment]
@wiedi excuse my lack of familiarity here, but when I look at https://apidocs.joyent.com/cloudapi/#images-2 I see that the public API includes "tags	Object	(New in 7.1.) An object of key/value pairs that allows clients to categorize images by any given criteria."

Looking at createImage and the other functions here, tags looks fully wired in, https://github.com/joyent/sdc-imgapi/blob/master/lib/images.js#L900 .

Does this help?

**Comment by wiedi** [comment]
Oh this is perfect! Thanks
